Planning-Inspectorate/template-app-service

- packer/build.pkr.hcl
> Changing packer image naming

- infrastructure/action-group.tf
- infrastructure/container-registry.tf
- infrastructure/locals.tf
Adding terraform configuration to create action group for template-app-service
> creating action groups

- infrastructure/pipelines/terraform-cd.yaml
- infrastructure/pipelines/terraform-ci-commit.yaml
- infrastructure/pipelines/terraform-ci.yaml
> correcting yaml file syntax errors

- infrastructure/data.tf
- infrastructure/environments/dev.tfvars
- infrastructure/locals.tf
- infrastructure/variables.tf
> Adding action Ids

- infrastructure/environments/dev.tfvars
- infrastructure/networking.tf
- infrastructure/variables.tf
Adding subnet resource configuration and subnet address
> Adding subnet to web app

- infrastructure/environments/dev.tfvars
> correcting subnet address space

- infrastructure/environments/dev.tfvars
> updating apps_subnet_address_space

- infrastructure/database.tf
- infrastructure/locals.tf
- infrastructure/main.tf
- infrastructure/monitoring.tf
> Adding key-vault for SQL and monitoring configuration

- infrastructure/app-web.tf
- infrastructure/variables.tf
> creating web-app and enabling alerts

- infrastructure/app-web.tf
- infrastructure/database.tf
> Adding sql admin connection string

- infrastructure/environments/dev.tfvars
- infrastructure/front-door-web.tf
- infrastructure/variables.tf
> adding azure front door and enabling alerts 

- infrastructure/front-door-web.tf
> changing sku for front door

- infrastructure/environments/dev.tfvars
> changing app service plan sku

- infrastructure/front-door-web.tf
> Removing managed rules from Front door firewall policy

- app/Dockerfile
- infrastructure/app-web.tf
- infrastructure/environments/dev.tfvars
> Adding Dockerfile and changing app service sku 

- package-lock.json
- package.json
> changing package-lock json file path

- azure-pipelines-build.yml
- azure-pipelines-deploy.yml
- packer/pipelines/purge-older-images.yml
> remove packer directory from app pipelines

- app/Dockerfile
> Dockerfile update

- app/Dockerfile
> updating base image in dockerfile

- infrastructure/app-web.tf
> adding hostname to web app

- packer/infra/environments/dev.tfvars
> changing the vnet sizing to test if resources are effected

- packer/pipelines/infra-cd.yml
> changing branching strategy to remove dependson plan temporarily

- packer/infra/main.tf
> changing vnet name

- packer/infra/main.tf
> create the vmss

- app/src/app/pages/home/home.view.njk
- azure-pipelines-build.yml
- azure-pipelines-ci.yml
- azure-pipelines-deploy.yml
- infrastructure/pipelines/terraform-cd.yaml
- infrastructure/pipelines/terraform-ci-commit.yaml
- infrastructure/pipelines/terraform-ci.yaml
Updating below pipelines to refer tag release/3.18.1 of common-pipelines-template
1. azure-pipelines-build.yml
2. azure-pipelines-ci.yml
3. azure-pipelines-deploy.yml
4. terraform-cd.yaml
5. terraform-ci-commit.yaml
6. terraform-ci.yaml
Issue ticket number: DEV-273
Issue ticket link: https://pins-ds.atlassian.net/browse/DEV-273
> Updating pipeline tags to release/3.18.1 

- packer/image-build/build.pkr.hcl
> new image without terraform in the name

- infrastructure/app-web.tf
- infrastructure/networking.tf
> Add health var

- infrastructure/front-door-premium.tf
- infrastructure/front-door-web-classic.tf
> Test: Adding custom domain to premium front door 

- infrastructure/app-web.tf
- infrastructure/environments/dev.tfvars
- infrastructure/variables.tf
> Updating Azure Easy Authentication configurations

- .pre-commit-config.yaml
- infrastructure/.terraform.lock.hcl
- infrastructure/main.tf
- infrastructure/providers.tf
- packer/infra/.terraform.lock.hcl
- packer/infra/main.tf
- packer/infra/providers.tf
Includes updates for the following 
1. pre-commit-terraform  to version 1.97.3
2. hashi/corp/azurerm to v>=4.18.0
3. claranet/regions/azurerm to v7.3.1
> Upgrading AzureRM to latest versions

- infrastructure/.tflint.hcl
- infrastructure/providers.tf
- packer/infra/providers.tf
> Upgarding terraform versions

- app/src/app/pages/home/home.view.njk
- app/src/app/pages/post/post.controller.js
- app/src/app/pages/post/post.view.njk
- app/src/app/routes/router.js
> feat(app): add example POST endpoint

- azure-pipelines-build.yml
- azure-pipelines-ci.yml
- azure-pipelines-deploy.yml
- azure-pipelines-variables.yml
- infrastructure/.terraform.lock.hcl
- infrastructure/app-web.tf
- infrastructure/environments/dev.tfvars
- infrastructure/pipelines/terraform-cd.yaml
- infrastructure/pipelines/terraform-ci-commit.yaml
- infrastructure/pipelines/terraform-ci.yaml
> adding git verify pipeline and updating  infra module version 

- infrastructure/.terraform.lock.hcl
> adding terraform lock changes

- infrastructure/.terraform.lock.hcl
- infrastructure/providers.tf
Updating AzureRM to latest version 4.26.0 as part of monthly infrastructure updates
terraform latest version is 1.11.3 which is included with in the required condition [">= 1.7.3, < 1.12.0"]
> Updating AzureRM version to latest

- infrastructure/.terraform.lock.hcl
- infrastructure/providers.tf
Updating AzureRM to latest version 4.28.0
> Upgrading azurerm to latest version

- infrastructure/app-web.tf
1.46 include excluded path set as optional for easy auth
> Updating latest infra module tag
